package ar.edu.unlu.corazones.modelo;

public enum EventosCorazones {
	CARTAS_REPARTIDAS,
	PEDIR_CARTA,
	JUGAR_2_DE_TREBOL,
	CARTA_TIRADA_INVALIDA,
	CARTA_TIRADA_INVALIDA_2_DE_TREBOL,
	PERDEDOR_JUGADA,
	CORAZONES_ROTOS,
	CARTA_TIRADA_VALIDA
}
